Repository kubernetes/heapster, pull requests merged in 2018-04, with the labels that each got.

#1996 delete .travis.yml
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2009 fix unkeyed fields error
  metrics/sinks/riemann/driver_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2011 Remove crassirostris from owners
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2008 Fix negative value on "disk/io_{read,write}_bytes_rate"
  metrics/processors/rate_calculator.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2012 Update influxdb.md
  docs/influxdb.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1999 Add local ephemeral storage metric into heapster
  docs/storage-schema.md
  metrics/core/metrics.go
  metrics/heapster.go
  metrics/processors/node_autoscaling_enricher.go
  metrics/processors/pod_based_enricher.go
  metrics/processors/pod_based_enricher_test.go
  metrics/sinks/stackdriver/metadata.go
  metrics/sinks/stackdriver/stackdriver.go
  metrics/sinks/stackdriver/stackdriver_test.go
  metrics/sources/summary/summary.go
  metrics/sources/summary/summary_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2020 Some typo fixes: reccomend->recommend /kubernetes in capital
  docs/model.md
  docs/source-configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2026 Correct the format
  docs/riemann.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2027 Fix stackdriver metrics for node memory using wrong metric type
  metrics/sinks/stackdriver/stackdriver.go
  metrics/sinks/stackdriver/stackdriver_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2028 [release-1.5] Fix stackdriver metrics for node memory using wrong metric type
  metrics/sinks/riemann/driver_test.go
  metrics/sinks/stackdriver/stackdriver.go
  metrics/sinks/stackdriver/stackdriver_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2033 Bump Heapster to version 1.5.3
  Makefile
  deploy/kube-config/google/heapster.yaml
  deploy/kube-config/influxdb/heapster.yaml
  deploy/kube-config/standalone-test/heapster-controller.yaml
  deploy/kube-config/standalone-test/heapster-summary-controller.yaml
  deploy/kube-config/standalone-with-apiserver/heapster-deployment.yaml
  deploy/kube-config/standalone/heapster-controller.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
