Repository kubernetes/heapster, pull requests merged in 2018-07, with the labels that each got.

#2054 Small typo fix: convertion->conversion
  docs/sink-configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1993 Update influxdb and grafana dependencies
  deploy/kube-config/influxdb/grafana.yaml
  deploy/kube-config/influxdb/influxdb.yaml
  grafana/Makefile
  grafana/README.md
  grafana/RELEASES.md
  influxdb/Makefile
  influxdb/RELEASES.md
Labels: approved, cncf-cla: yes, lgtm, sink/influxdb, size/M

#2057 Add an option to read Host ID from node annotation if ExternalID is not available
  events/sinks/factory.go
  metrics/sinks/factory.go
  metrics/sources/summary/summary.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#2060 Typo fix: architecures->architectures
  grafana/README.md
  influxdb/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1961 Uses mean instead of sum in Grafana queries to avoid plotting variations at different timescale
  grafana/dashboards/cluster.json
  grafana/dashboards/pods.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#2064 #2062 - improve documentation describing cumulative CPU usage metric
  docs/storage-schema.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2068 Release Heapster 1.6-beta.1
  Makefile
  deploy/kube-config/google/heapster.yaml
  deploy/kube-config/influxdb/heapster.yaml
  deploy/kube-config/standalone-test/heapster-controller.yaml
  deploy/kube-config/standalone-test/heapster-summary-controller.yaml
  deploy/kube-config/standalone-with-apiserver/heapster-deployment.yaml
  deploy/kube-config/standalone/heapster-controller.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#2069 Bump Kubernetes version used in integration tests to fix presubmits
  Makefile
  deploy/kube-config/standalone-test/heapster-controller.yaml
  deploy/kube-config/standalone-test/heapster-rbac.yaml
  deploy/kube-config/standalone-test/heapster-service-account.yaml
  integration/.jenkins.sh
  integration/framework.go
  integration/heapster_api_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2071 Bump Heapster to v1.5.4
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2074 Revert Heapster version in deployment files to 1.5.4
  deploy/kube-config/google/heapster.yaml
  deploy/kube-config/influxdb/heapster.yaml
  deploy/kube-config/standalone-test/heapster-controller.yaml
  deploy/kube-config/standalone-with-apiserver/heapster-deployment.yaml
  deploy/kube-config/standalone/heapster-controller.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
