Repository kubernetes/heapster, pull requests merged in 2018-03, with the labels that each got.

#1971 fix removed quotes from statsd example
  docs/sink-configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1974 Typo fix "are"->"is"
  docs/storage-schema.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1975 Use float64 instead of float32 for metrics of Float type
  metrics/core/types.go
  metrics/processors/node_autoscaling_enricher.go
  metrics/processors/rate_calculator.go
  metrics/sinks/stackdriver/stackdriver_test.go
  metrics/sources/kubelet/kubelet.go
  metrics/sources/summary/summary.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1977 Use float64 instead of float32 for metrics of Float type
  metrics/core/types.go
  metrics/processors/node_autoscaling_enricher.go
  metrics/processors/rate_calculator.go
  metrics/sinks/stackdriver/stackdriver_test.go
  metrics/sources/kubelet/kubelet.go
  metrics/sources/summary/summary.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1978 Bump Heapster to version 1.5.2
  Makefile
  deploy/kube-config/google/heapster.yaml
  deploy/kube-config/influxdb/heapster.yaml
  deploy/kube-config/standalone-test/heapster-controller.yaml
  deploy/kube-config/standalone-with-apiserver/heapster-deployment.yaml
  deploy/kube-config/standalone/heapster-controller.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1979 Bump heapster-summary-controller version to v1.5.2
  deploy/kube-config/standalone-test/heapster-summary-controller.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1981 Export node cpu metrics in whole cores
  metrics/sinks/stackdriver/stackdriver.go
  metrics/sinks/stackdriver/stackdriver_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1983 Export node cpu metrics in whole cores
  metrics/sinks/stackdriver/stackdriver.go
  metrics/sinks/stackdriver/stackdriver_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1982 Update debugging.md
  docs/debugging.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1984 Typo fix in influxdb.md
  docs/influxdb.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1989 add cpu load metrics
  docs/storage-schema.md
  metrics/core/metrics.go
Labels: approved, cncf-cla: yes, lgtm, size/S
