Repository kubernetes/heapster, pull requests merged in 2018-02, with the labels that each got.

#1914 Hawkular, reduce the sink's memory usage in definition caching
  Godeps/Godeps.json
  metrics/sinks/hawkular/client.go
  metrics/sinks/hawkular/driver.go
  metrics/sinks/hawkular/driver_test.go
  metrics/sinks/hawkular/types.go
  vendor/github.com/hawkular/hawkular-client-go/metrics/client.go
Labels: cncf-cla: yes, size/L

#1920 Remove docs/google.md
  docs/google.md
Labels: cncf-cla: yes, lgtm, sink/gcm, size/S

#1950 [Kafka Sink] Clean function name
  common/kafka/kafka.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#1940 Fix nil pointer dereference when a sink return (nil, err)
  events/sinks/factory.go
  metrics/sinks/factory.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#1963 Add OWNERS files
  OWNERS
  events/sinks/elasticsearch/OWNERS
  events/sinks/gcl/OWNERS
  events/sinks/honeycomb/OWNERS
  events/sinks/influxdb/OWNERS
  events/sinks/kafka/OWNERS
  events/sinks/riemann/OWNERS
  metrics/sinks/elasticsearch/OWNERS
  metrics/sinks/gcm/OWNERS
  metrics/sinks/graphite/OWNERS
  metrics/sinks/hawkular/OWNERS
  metrics/sinks/honeycomb/OWNERS
  metrics/sinks/influxdb/OWNERS
  metrics/sinks/kafka/OWNERS
  metrics/sinks/librato/OWNERS
  metrics/sinks/opentsdb/OWNERS
  metrics/sinks/riemann/OWNERS
  metrics/sinks/stackdriver/OWNERS
  metrics/sinks/statsd/OWNERS
  metrics/sinks/wavefront/OWNERS
Labels: cncf-cla: yes, size/L

#1965 [infra] Add Influx owners to the Grafana directory
  grafana/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1933 add github templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/M
