Repository kubernetes/heapster, pull requests merged in 2018-05, with the labels that each got.

#2030 Typo fix: seperated->separated
  docs/storage-schema.md
  metrics/util/label_copier.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2034 deploy: update all references to container images to v1.5.3
  deploy/kube-config/google/heapster.yaml
  deploy/kube-config/influxdb/heapster.yaml
  deploy/kube-config/standalone-test/heapster-controller.yaml
  deploy/kube-config/standalone-test/heapster-summary-controller.yaml
  deploy/kube-config/standalone-with-apiserver/heapster-deployment.yaml
  deploy/kube-config/standalone/heapster-controller.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#2035 Typo fix: limitted->limited
  docs/maintenance.md
  metrics/sinks/influxdb/influxdb_historical.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1995 Exports metrics to track non primary container resource requests
  docs/storage-schema.md
  metrics/core/metrics.go
  metrics/processors/pod_based_enricher.go
  metrics/processors/pod_based_enricher_test.go
  metrics/sinks/stackdriver/metadata.go
  metrics/sinks/stackdriver/stackdriver.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2022 Mark Heapster as Deprecated
  README.md
  docs/deprecation.md
Labels: approved, cncf-cla: yes, do-not-merge/hold, sig/instrumentation, size/M

#1964 Fix grafana dashboards. Fixes #1958
  grafana/dashboards/cluster.json
  grafana/dashboards/pods.json
Labels: approved, cncf-cla: yes, lgtm, size/XS
