Repository kubernetes/heapster, pull requests merged in 2018-08, with the labels that each got.

#2073 Bump Heapster version in deployment files
  deploy/kube-config/google/heapster.yaml
  deploy/kube-config/influxdb/heapster.yaml
  deploy/kube-config/standalone-test/heapster-controller.yaml
  deploy/kube-config/standalone-with-apiserver/heapster-deployment.yaml
  deploy/kube-config/standalone/heapster-controller.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#2078 Fixed syntax
  docs/source-configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2052 Allow users to manually configure the Stackdriver sink to restore metric ingestion and stop the crash loop when not running in GCP.
  metrics/sinks/stackdriver/stackdriver.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2082 change the func name of creating influxdb sink
  metrics/sinks/influxdb/influxdb.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2081 change the condition of sending data in influxdb sink
  metrics/sinks/influxdb/influxdb.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2083 Typo fix: encoraged->encouraged
  docs/deprecation.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
